export const DEFAULT_SETTINGS = {
  storeName: "The Wooden Tone",
  tagline: "Solid Wood Furniture",
  phone: "+91 00000 00000",
  whatsapp: "910000000000",
  email: "hello@thewoodentone.com",
  address: "Showroom address — update in Admin → Settings",
  hours: "Mon – Sat · 10:00 AM – 7:00 PM",
  mapEmbedUrl: "",
  mapLink: "",
  announcements: [
    "Handcrafted Solid Wood Furniture",
    "Free Shipping Across India",
    "Up to 50% OFF on Every Category",
    "शुद्ध लकड़ी का हस्तनिर्मित फर्नीचर",
    "Secure Payments · Easy Returns",
  ],
  marquee: ["Solid Wood", "Handcrafted", "Made to Last", "Free Shipping", "Sheesham · Teak · Mango"],
  social: { facebook: "", instagram: "https://instagram.com/thewoodentone", x: "", linkedin: "" },
  instagramHandle: "@thewoodentone",
  footerAbout: "We provide the best solid wood furniture across India & beyond — crafted to last for generations.",
  shippingFee: 0,
  freeShippingAbove: 0,
  codEnabled: true,
  codFee: 0,
  codMaxOrder: 200000,
  razorpayEnabled: false,
  razorpayKeyId: "",
  razorpayKeySecret: "",
  razorpayWebhookSecret: "",
  phonepeEnabled: false,
  phonepeClientId: "",
  phonepeClientSecret: "",
  phonepeClientVersion: "1",
  phonepeEnv: "SANDBOX",
  storyHeading: "Designed in Wood, Built for Living",
  storyText:
    "The Wooden Tone is a dedicated furniture manufacturer specialising in high-quality wooden furniture. Every piece is shaped by skilled craftsmen and finished by hand, so it feels warm on day one and only gets better with time.",
  aboutHeading: "Furniture that grows more beautiful with time",
  aboutText:
    "The Wooden Tone is a dedicated furniture manufacturer specialising in high-quality wooden furniture. From beds and wardrobes to spice racks and pooja décor, every piece is made by skilled craftsmen using seasoned solid wood.\n\nWe provide the best furniture across India & beyond — with free shipping, secure payments and support that's there when you need it.",
  aboutImage: "/seed/products/arm-2.jpg",
  homeSections: [
    { eyebrow: "Shop Beds", title: "Beds", categories: ["beds", "bedroom-wardrobes"] },
    { eyebrow: "Shop Armchairs", title: "Armchairs & Rocking Chairs", categories: ["armchairs", "rocking-chairs", "bar-stool", "sofa"] },
    { eyebrow: "Shop Tables", title: "Console & Center Tables", categories: ["console-sofa-tables", "center-table", "coffee-table", "end-table"] },
    { eyebrow: "Shop Storage", title: "Bookcase & Storage", categories: ["bookcase", "wall-shelves", "dressers-chests", "desk"] },
    { eyebrow: "Kitchen & Decor", title: "Kitchen, Dining & Decor", categories: ["spice-racks", "beer-mugs", "incense-holders", "jars-containers", "pooja-supplies"] },
  ] as { eyebrow: string; title: string; categories: string[] }[],
  instagramImages: [] as string[],
  customOrderImage: "/seed/products/beds-3.jpg",
  seoTitle: "The Wooden Tone — Handcrafted Solid Wood Furniture",
  seoDescription: "Beds, sofas, dining sets and décor crafted from sheesham, teak and mango wood — delivered free across India.",
};

export type Settings = typeof DEFAULT_SETTINGS;
export const SECRET_KEYS = ["razorpayKeySecret", "razorpayWebhookSecret", "phonepeClientSecret"] as const;
